# Generated by Django 2.0.5 on 2018-05-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='contain',
            new_name='containt',
        ),
    ]
