# Generated by Django 2.0.5 on 2018-07-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('blog', '0003_auto_20180604_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('containt', models.CharField(blank=True, max_length=99999999, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('userprofile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_comment', models.CharField(blank=True, max_length=999999, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('blog', models.ManyToManyField(to='blog.Blog')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_comment', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Blog_like', to='core.UserProfile')),
            ],
        ),
        migrations.DeleteModel(
            name='Bucketlist',
        ),
    ]
